### ISSUE TITLE
Cookie Lifetime Limits

### ISSUE THREAD

**Issue by arichiv** [johannhof/draft-annevk-johannhof-httpbis-cookies#8]
Should the section on [Cookie Lifetime Limits](https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#section-5.5) be included in this new proposal? I noticed it's missing from the current iteration.

**Comment by johannhof** [comment]
cc @sbingler

@annevk do you know if we decided to remove this for some reason? I don't recall it, but I may be missing something.

**Comment by annevk** [comment]
Is this not encoded through [Cookie Store And Limits](https://johannhof.github.io/draft-annevk-johannhof-httpbis-cookies/draft-annevk-johannhof-httpbis-cookies.html#name-cookie-store-and-limits) and their callers?

**Comment by johannhof** [comment]
Ah, yes, it seems to be. @arichiv any concerns with that? You can see the `cookie age limit` being used in the other algorithms.

**Comment by arichiv** [comment]
LGTM, I missed the new location when skimming before
